export APP_MODULES += hello_world 
export APP_MODULES += libtest_shared 
export APP_MODULES += libtest_static 
export APP_MODULES += test_shared
export APP_MODULES += test_static
export APP_MODULES += link_reversely
export APP_MODULES += find_duplicated_num
export APP_MODULES += insert_sort 
export APP_MODULES += ipstr_2_ipint
export APP_MODULES += ipstr_2_ipint
export APP_MODULES += raw_socket_test
export APP_MODULES += raw_socket_test_ipdump

#c++
export APP_MODULES += class
export APP_MODULES += data_read
export APP_MODULES += Inheritace_main
export APP_MODULES += Inheritace_simple
export APP_MODULES += reference_test 
export APP_MODULES += string_sample_cpp 
export APP_MODULES += map_test 
export APP_MODULES += rsa_verify 
export APP_MODULES += motor_ctr 
export APP_MODULES += new_test
